# Generated by Django 4.1.3 on 2022-11-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_riderecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterField(
            model_name='riderecord',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
